#
# See the guidelines for updating this recipe for new releases:
# https://github.com/scrapy/scrapy/wiki/Scrapy-release-procedure#conda-packages
#
{% set name = "Scrapy" %}
{% set version = "2.14.1" %}
{% set sha256 = "b2a4e61802e0a5518bc8293058adedbb6b0d51c08c125d1322b1af7c7cbca4c1" %}
{% set blake2b256 = "0305db301a334044577e2f341b19631229aae06f4664dc4c6c3c6246b4081872" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/db/fb/0ccc11eaabdac1f210f27fb6b2ad4aa4ff8a5085cbc616102536fe2c56f4/scrapy-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  noarch: python
  entry_points:
    - scrapy = scrapy.cmdline:execute

# The requirements below shall match the requirements from the target package
# version (check setup.py for changes).
requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling

  run:
    - python >={{ python_min }}
    # pywin32 exists for unix as a noop package
    - pywin32

    # Same order as setup.py:
    - twisted >=21.7.0,<=25.5.0
    - cryptography >=37.0.0
    - cssselect >=0.9.1
    - defusedxml >=0.7.1
    - itemadapter >=0.1.0
    - itemloaders >=1.0.1
    - lxml >=4.6.4
    - packaging
    - parsel >=1.5.0
    - protego >=0.1.15
    - pyOpenSSL >=22.0.0
    - queuelib >=1.4.2
    - service_identity >=18.1.0
    - tldextract
    - w3lib >=1.17.0
    - zope.interface >=5.1.0
    - pydispatcher >=2.0.5

test:
  requires:
    - python {{ python_min }}
    - attrs
    - botocore
    - brotli >=1.2.0
    - bpython  # [not win]
    - ipython
    - google-cloud-storage
    - pip
    - jmespath
    - pexpect
    - pillow
    - pyftpdlib
    - pytest >=8.4.1
    - pytest-twisted
    - testfixtures
    - priority >=1.1.0,<2.0
    - sybil
    - setuptools-scm   # required indirectly by pytest-forked
  source_files:
    - conftest.py
    - pyproject.toml
    - scrapy
    - tests
  commands:
    - scrapy version -v
    - mv scrapy _scrapy
    - pytest _scrapy tests

about:
  home: https://scrapy.org/
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: A high-level Python Screen Scraping framework
  description: |
    Scrapy is an open source and collaborative framework for extracting the
    data you need from websites in a fast, simple, yet extensible way.
  doc_url: https://docs.scrapy.org
  dev_url: https://github.com/scrapy/scrapy

extra:
  recipe-maintainers:
    - rmax
    - kmike
    - Gallaecio
    - wRAR
    - dangra
