#
# See the guidelines for updating this recipe for new releases:
# https://github.com/scrapy/scrapy/wiki/Scrapy-release-procedure#conda-packages
#
{% set name = "Scrapy" %}
{% set version = "2.13.3" %}
{% set sha256 = "bf17588c10e46a9d70c49a05380b749e3c7fba58204a367a5747ce6da2bd204d" %}
{% set blake2b256 = "be6cbab0c01c5c50842548f0b5e936dfd2520a1ce84c171472c2cfe4d0599841" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/{{ blake2b256[:2] }}/{{ blake2b256[2:4] }}/{{ blake2b256[4:] }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  noarch: python
  entry_points:
    - scrapy = scrapy.cmdline:execute

# The requirements below shall match the requirements from the target package
# version (check setup.py for changes).
requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling

  run:
    - python >={{ python_min }}
    # pywin32 exists for unix as a noop package
    - pywin32

    # Same order as setup.py:
    - twisted >=21.7.0
    - cryptography >=37.0.0
    - cssselect >=0.9.1
    - itemloaders >=1.0.1
    - parsel >=1.5.0
    - pyOpenSSL >=22.0.0
    - queuelib >=1.4.2
    - service_identity >=18.1.0
    - w3lib >=1.17.0
    - zope.interface >=5.1.0
    - protego >=0.1.15
    - itemadapter >=0.1.0
    - packaging
    - tldextract
    - lxml >=4.6.0
    - defusedxml >=0.7.1
    - pydispatcher >=2.0.5

test:
  requires:
    - python {{ python_min }}
    - attrs
    - botocore
    - brotli
    - bpython  # [not win]
    - dataclasses
    - ipython
    - google-cloud-storage
    - mitmproxy
    - pip
    - jmespath
    - pexpect
    - pillow
    - pytest >=8.4.1
    - testfixtures
    - priority >=1.1.0,<2.0
    - sybil
    - setuptools-scm   # required indirectly by pytest-forked
  source_files:
    - conftest.py
    - scrapy
    - tests
  commands:
    - scrapy version -v
    - mv scrapy _scrapy
    # https://github.com/scrapy/scrapy/issues/2653#issuecomment-598610517
    - rm -f tests/test_command_parse.py tests/test_commands.py tests/test_crawler.py tests/test_downloader_handlers.py tests/test_downloader_handlers_http2.py  # [osx]
    # Test failures since Scrapy 2.4:
    - rm -f tests/test_command_check.py tests/test_command_parse.py tests/test_commands.py tests/test_crawler.py tests/test_feedexport.py
    # test_convert_image fails because expected vs actual color does not match
    # by 1 bit (#0079FF vs #0080FF)
    - rm -f tests/test_pipeline_images.py
    # MediaPipelineDeprecatedMethodsTestCase leaves files that interfere with its tests
    - rm -f tests/test_pipeline_media.py
    # The removed tests/test_pipeline_media.py file is a dependency
    - rm -f tests/test_pipeline_files.py
    # Started failing in 2.11.1
    - rm -f tests/test_command_shell.py
    # Tests need to be fixed in upstream.
    - pytest _scrapy tests

about:
  home: https://scrapy.org/
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: A high-level Python Screen Scraping framework
  description: |
    Scrapy is an open source and collaborative framework for extracting the
    data you need from websites in a fast, simple, yet extensible way.
  doc_url: https://docs.scrapy.org
  dev_url: https://github.com/scrapy/scrapy

extra:
  recipe-maintainers:
    - rmax
    - kmike
    - Gallaecio
    - wRAR
    - dangra
