#
# See the guidelines for updating this recipe for new releases:
# https://github.com/scrapy/scrapy/wiki/Scrapy-release-procedure#conda-packages
#
{% set name = "Scrapy" %}
{% set version = "1.7.4" %}
{% set hash_type = "sha256" %}
{% set hash_val = "f0813d23a3f5659f403f469b11488ecd81e989e834205c4366cd231536496513" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0

# The requirements below shall match the requirements from the target package
# version (check setup.py for changes).
requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - setuptools
    - twisted >=13.1.0  # [not py34 and not win]
    - twisted >=13.1.0,<=19.2.0  # [py34 and not win]
    - twisted >=16.4.0  # [win]
    - w3lib >=1.17.0
    - queuelib
    - lxml  # [not py34]
    - lxml <=4.3.5  # [py34]
    - pyopenssl
    - cssselect >=0.9
    - six >=1.5.2
    - parsel >=1.5.0
    - pydispatcher >=2.0.5
    - service_identity
    - pywin32  # [win]

test:
  requires:
    - {{ compiler('c') }}
    - {{ compiler("cxx") }}
    - brotlipy  # [win]
    - pip
  source_files:
    - conftest.py
    - requirements-py2.txt
    - requirements-py3.txt
    - scrapy
    - tests
  commands:
    - scrapy version  # [not win]
    - sed -i '/brotlipy/d' tests/requirements-py2.txt  # [win]
    - pip install -ctests/constraints.txt -rrequirements-py2.txt botocore google-cloud-storage Pillow!=3.0.0 -rtests/requirements-py2.txt  # [py27]
    - pip install -ctests/constraints.txt -rrequirements-py3.txt Pillow -rtests/requirements-py3.txt  # [py3k]
    - mv scrapy _scrapy
    - rm tests/test_command_parse.py tests/test_command_shell.py tests/test_commands.py tests/test_crawler.py tests/test_downloader_handlers.py tests/test_exporters.py tests/test_feedexport.py tests/test_proxy_connect.py tests/test_utils_trackref.py  # [win]
    - rm tests/test_command_parse.py tests/test_commands.py tests/test_crawler.py tests/test_downloader_handlers.py  # [osx]
    - pytest _scrapy tests

about:
  home: https://scrapy.org/
  license: BSD 3-Clauses
  license_file: LICENSE
  summary: A high-level Python Screen Scraping framework
  description: |
    Scrapy is an open source and collaborative framework for extracting the
    data you need from websites in a fast, simple, yet extensible way.
  doc_url: https://docs.scrapy.org
  dev_url: https://github.com/scrapy/scrapy

extra:
  recipe-maintainers:
    - rmax
    - redapple
    - kmike
    - Gallaecio
    - wRAR
    - dangra
