#
# See the guidelines for updating this recipe for new releases:
# https://github.com/scrapy/scrapy/wiki/Scrapy-release-procedure#conda-packages
#
{% set name = "Scrapy" %}
{% set version = "2.0.1" %}
{% set hash_type = "sha256" %}
{% set hash_val = "85581a01f4160a103ca9906ffa4e44474f4ecd1685f0934728892c58ebf111f6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  skip: True  # [py2k]

# The requirements below shall match the requirements from the target package
# version (check setup.py for changes).
requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - setuptools
    - twisted >=17.9.0
    - w3lib >=1.17.0
    - queuelib
    - lxml
    - cryptography >=2
    - cssselect >=0.9
    - parsel >=1.5.0
    - pydispatcher >=2.0.5
    - service_identity
    - pywin32  # [win]
    - protego

test:  # [not win]
  requires:
    - botocore
    - brotlipy
    - bpython  # [not win]
    - ipython
    - google-cloud-storage
    - pip
    - jmespath
    - pillow
    - pytest < 5.4
    - testfixtures
    # indirect dependencies, to avoid compilation
    - zstandard <0.13.0, >=0.11.0
  source_files:
    - conftest.py
    - scrapy
    - tests
  commands:
    - scrapy version  # [not win]
    - pip install setuptools-scm  # required by indirect dependency pytest-forked
    # required from tests/requirements-py3.txt unavailable on conda:
    - pip install mitmproxy pytest-twisted sybil  # [not win or not py==38]
    - pip install pytest-twisted sybil  # [win and py==38]
    - mv scrapy _scrapy
    - rm tests/test_proxy_connect.py  # [win or py==38]
    # https://github.com/scrapy/scrapy/issues/2653#issuecomment-598610517
    - rm tests/test_utils_asyncio.py  # [win or py==38]
    - rm tests/test_command_parse.py tests/test_command_shell.py tests/test_commands.py tests/test_crawl.py tests/test_crawler.py tests/test_downloader_handlers.py tests/test_exporters.py tests/test_feedexport.py tests/test_utils_trackref.py  # [win]
    - rm tests/test_command_parse.py tests/test_commands.py tests/test_crawler.py tests/test_downloader_handlers.py  # [osx]
    - pytest _scrapy tests

about:
  home: https://scrapy.org/
  license: BSD 3-Clauses
  license_file: LICENSE
  summary: A high-level Python Screen Scraping framework
  description: |
    Scrapy is an open source and collaborative framework for extracting the
    data you need from websites in a fast, simple, yet extensible way.
  doc_url: https://docs.scrapy.org
  dev_url: https://github.com/scrapy/scrapy

extra:
  recipe-maintainers:
    - rmax
    - redapple
    - kmike
    - Gallaecio
    - wRAR
    - dangra
