#
# See the guidelines for updating this recipe for new releases:
# https://github.com/scrapy/scrapy/wiki/Scrapy-release-procedure#conda-packages
#
{% set name = "Scrapy" %}
{% set version = "2.4.1" %}
{% set hash_val = "68c48f01a58636bdf0f6fcd5035a19ecf277b58af24bd70c36dc6e556df3e005" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash_val }}

build:
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0
  skip: true  # [py2k]
  entry_points:
    - scrapy = scrapy.cmdline:execute

# The requirements below shall match the requirements from the target package
# version (check setup.py for changes).
requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - setuptools
    - pywin32  # [win]

    # Same order as setup.py:
    - twisted >=17.9.0
    - cryptography >=2.0
    - cssselect >=0.9.1
    - itemloaders >=1.0.1
    - lxml >=3.5.0
    - parsel >=1.5.0
    - pydispatcher >=2.0.5
    - pyOpenSSL >=16.2.0
    - queuelib >=1.4.2
    - service_identity >=16.0.0
    - w3lib >=1.17.0
    - zope.interface >=4.1.3
    - protego >=0.1.15
    - itemadapter >=0.1.0

test:
  requires:
    - attrs
    - botocore
    - brotlipy
    - bpython  # [not win]
    - dataclasses  # [py!=35]
    - ipython
    - google-cloud-storage
    - pip
    - jmespath
    - pillow
    - pytest < 5.4
    - testfixtures
    # indirect dependencies, to avoid compilation
    - zstandard <0.13.0, >=0.11.0
  source_files:
    - conftest.py
    - scrapy
    - tests
  commands:
    - scrapy version -v
    - pip install setuptools-scm  # required by indirect dependency pytest-forked
    # required from tests/requirements-py3.txt unavailable on conda:
    - pip install mitmproxy pytest-twisted sybil  # [not win or not py==38]
    - pip install pytest-twisted sybil  # [win and py==38]
    - mv scrapy _scrapy
    - rm tests/test_command_check.py tests/test_command_parse.py tests/test_commands.py  # permission issues
    - rm tests/test_proxy_connect.py  # [win or py==38]
    # https://github.com/scrapy/scrapy/issues/2653#issuecomment-598610517
    - rm tests/test_utils_asyncio.py  # [win or py==38]                                                                                                                                                            # [win]
    - rm -f tests/test_command_parse.py tests/test_commands.py tests/test_crawler.py tests/test_downloader_handlers.py  # [osx]
    # Test failures since Scrapy 2.4:
    - rm -f tests/test_crawler.py tests/test_feedexport.py
    # Tests need to be fixed in upstream.
    - pytest _scrapy tests

about:
  home: https://scrapy.org/
  license: BSD-3-Clause-Clear
  license_file: LICENSE
  summary: A high-level Python Screen Scraping framework
  description: |
    Scrapy is an open source and collaborative framework for extracting the
    data you need from websites in a fast, simple, yet extensible way.
  doc_url: https://docs.scrapy.org
  dev_url: https://github.com/scrapy/scrapy

extra:
  recipe-maintainers:
    - rmax
    - kmike
    - Gallaecio
    - wRAR
    - dangra
