appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dqcaNu92goMJkugjz8UWsOXql+1IYTxpBQBUOhIiTfXnTtaO5Wyz7x8I/tpkoyMyj16kxjgQMu42v+3WCsOnfltpHPqP/czEHbM5G0lL8zbiMnfKyVPQ47oeO8IR7Ia0GdD2WASce/RTNowhGCp0Ie/ojzui2DwdMGB2jrde+rvc++Cg7xUeApcv/pNFjkK3MpVlOS9IsfVIzGXqxXg/d9Ljoxpro15n9+tS0np4pI3X/9mOEfU7qnQ54EnJPhmRE9ATM3Ul6L9Kz1OvMlRe6UWigubxC6Os19r0bUnWkjldMz1k4+r+/g1OqLGxdO/3n8h6cOav32fjO0D4OqaTDh1+Ivi7DQ1jJ5fPGWjcYYKX49CfNh+K1mJ/5VnxpBdauU5Z2nU+JIm1gh4wzFu8RZxlH+9dV+7FOzCRSD5pJFlDFdhlGeFlMywPAHQnCSaAF8rplbGhgnwgmloxO5Z+MUqMJsc8tiaHX/AKCuCnejoZgcHVbVGg3KcRW+5Wu4+aFVJsA6LYOvvXGXIsOtlkm+hGqVX9Gv+nyaciAPUaTSPxkxExfA7VluY6J/aE+rpi3NpxIP1vw7mhRwJky/qvlZJ7qny50xpTaPDt25gKsf11SAE7zeQZUe7Zp+QVEkfu5wxst68U6XMXwFYk7tx/gxBf5XK8+pIby2955U6El5E=}
provider:
  win: azure
conda_forge_output_validation: true
